In [1]:
import os
import tensorflow as tf

from modules.run import load_config
from modules.run import Trainer
from modules.data import DataManager
from modules.models import pretrained_cnn

## Testing imports

import matplotlib.pyplot as plt
import numpy as np

In [2]:
config = load_config("cls_test")

In [3]:
data_manager = DataManager(config)

In [6]:
train_generator, val_generator, dataframe = data_manager.generate_kenya()

Found 900 validated image filenames belonging to 3 classes.
Found 99 validated image filenames belonging to 3 classes.


In [5]:
convnet = pretrained_cnn(config, image_size=config["image_size"], n_channels=config["n_channels"])

In [8]:
trainer = Trainer(config)

In [7]:
for i, class1 in train_generator:
    print(class1)
    break
for i, class1 in val_generator:
    print(class1)
    break

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [9]:
convnet.compile(loss=trainer.loss, optimizer=trainer.optimizer, weighted_metrics=config["weighted_metrics"])

convnet.summary()

convnet.fit_generator(
    train_generator, 
    epochs=config["n_epochs"],
    callbacks=trainer.callbacks, 
    validation_data=val_generator, 
    validation_steps=len(val_generator) // config["batch_size"],
    class_weight=data_manager.class_weight("kenya")
)

# convnet.fit_generator(
#         train_generator, 
#         config["sample"]["size"] * (1 - config["validation_split"]) // config["batch_size"],
#         epochs=config["n_epochs"],
#         callbacks=trainer.callbacks, 
#         validation_data=val_generator, 
#         validation_steps=config["sample"]["size"] * (config["validation_split"]) // config["batch_size"],
#         class_weight=data_manager.class_weight("kenya")
#     )


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
resnet50v2 (Model)           (None, 2048)              23564800  
_________________________________________________________________
flatten (Flatten)            (None, 2048)              0         
_________________________________________________________________
dense (Dense)                (None, 512)               1049088   
_________________________________________________________________
dropout (Dropout)            (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               262656    
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 1